<a href="https://colab.research.google.com/github/SarahAdmin/Data-Science-Project/blob/main/Currency_and_Top_Songs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('banknote-dimensions.csv')

In [4]:
df.eval('area = length * width')

               currency code  value  length  width     area
0        Argentine Peso  ARS      2   155.0   65.0  10075.0
1        Argentine Peso  ARS      5   155.0   65.0  10075.0
2        Argentine Peso  ARS     10   155.0   65.0  10075.0
3        Argentine Peso  ARS     20   155.0   65.0  10075.0
4        Argentine Peso  ARS     50   155.0   65.0  10075.0
..                  ...  ...    ...     ...    ...      ...
245  West African Franc  XOF    500   114.0   60.0   6840.0
246  West African Franc  XOF   1000   125.0   66.0   8250.0
247  West African Franc  XOF   2000   130.0   65.0   8450.0
248  West African Franc  XOF   5000   140.0   74.0  10360.0
249  West African Franc  XOF  10000   145.0   74.0  10730.0

[250 rows x 6 columns]

In [5]:
currencyOne = df.groupby(['currency','code'])

In [6]:
currencyOne.first()

                             value  length  width
currency               code
Argentine Peso         ARS       2   155.0  65.00
Australian Dollar      AUD       1   140.0  70.00
Bangladeshi Taka       BDT       2   100.0  60.00
Bolivian Boliviano     BOB      10   140.0  70.00
Canadian Dollar        CAD       5   152.4  69.85
Cape Verdean Escudo    CVE     200   125.0  63.00
Central African Franc  XAF     500   125.0  64.00
Chilean Peso           CLP    1000   120.0  70.00
Chinese Yuan           CNY       1   130.0  63.00
Colombian Peso         COP    2000   128.0  66.00
Costa Rican Colon      CRC    1000   125.0  67.00
Czech Koruna           CZK     100   140.0  69.00
Dobra                  STD       5   130.0  67.00
East Caribbean Dollar  XCD       5   145.0  69.00
Euro                   EUR       5   120.0  62.00
Georgian Lari          GEL       5   122.0  62.00
Icelandic Krona        ISK     500   145.0  70.00
Indonesian Rupiah      IDR    1000   121.0  65.00
Israeli New Shekel     ILS      20   129.0  71.00
Jamaican Dollar        JMD      50   145.0  68.00
Japanese Yen           JPY    1000   150.0  76.00
Korean Won             KRW    1000   136.0  68.00
Kyrgystani Som         KGS      20   120.0  58.00
Malawian Kwacha        MWK      20   128.0  64.00
New Zealand Dollar     NZD       5   135.0  66.00
Nigerian Naira         NGN       5   130.0  72.00
Papua New Guinean Kina PGK       2   140.0  70.00
Peruvian Sol           PEN      10   140.0  65.00
Peso Dominicano        DOP      50   156.0  67.00
Peso Mexicano          MXN      20   120.0  65.00
Peso Uruguayo          UYU      20   139.0  67.00
Philippine Piso        PHP      20   160.0  66.00
Pound Stirling         GBP       5   125.0  65.00
Serbian Dinar          RSD      10   131.0  62.00
South African Rand     ZAR      10   128.0  70.00
Swedish Krona          SEK      20   120.0  66.00
Tunisian Dinar         TND       5   143.0  70.00
Turkish Lira           TRY       5   130.0  64.00
US Dollar              USD       1   156.0  67.00
Ukrainian Hryvna       UAH      20   130.0  69.00
Venezuelan Bolivar     VES       5   156.0  69.00
West African Franc     XOF     500   114.0  60.00

In [7]:
currencyTwo = df.groupby(['currency']).agg(total_value=('value','sum'),
                                                avg_length=('length','mean'),
                                                avg_width=('width','mean'))

In [8]:
currencyTwo

                        total_value  avg_length  avg_width
currency
Argentine Peso                13887  155.000000  65.000000
Australian Dollar               188  143.571429  66.785714
Bangladeshi Taka               1887  128.444444  64.444444
Bolivian Boliviano              380  140.000000  70.000000
Canadian Dollar                 185  152.400000  69.850000
Cape Verdean Escudo            8700  135.800000  67.800000
Central African Franc         18500  135.000000  69.200000
Chilean Peso                  38000  134.000000  70.000000
Chinese Yuan                    186  142.500000  68.833333
Colombian Peso               187000  140.500000  66.000000
Costa Rican Colon             88000  142.500000  67.000000
Czech Koruna                   8800  155.000000  71.500000
Dobra                           385  142.666667  67.000000
East Caribbean Dollar           185  145.000000  69.000000
Euro                            885  140.000000  73.428571
Georgian Lari                   185  132.000000  66.000000
Icelandic Krona               16500  153.000000  70.000000
Indonesian Rupiah            188000  136.000000  65.000000
Israeli New Shekel              370  139.500000  71.000000
Jamaican Dollar                6650  145.000000  68.000000
Japanese Yen                  18000  155.000000  76.000000
Korean Won                    66000  145.000000  68.000000
Kyrgystani Som                 6870  138.000000  65.714286
Malawian Kwacha                8870  131.250000  65.250000
New Zealand Dollar              185  145.000000  70.000000
Nigerian Naira                 1885  140.750000  74.625000
Papua New Guinean Kina          187  140.000000  70.000000
Peruvian Sol                    380  140.000000  65.000000
Peso Dominicano                3850  156.666667  67.000000
Peso Mexicano                  1870  135.833333  65.000000
Peso Uruguayo                  3870  154.142857  72.000000
Philippine Piso                1870  160.000000  66.000000
Pound Stirling                   85  135.500000  71.000000
Serbian Dinar                  8880  145.222222  69.111111
South African Rand              380  140.000000  70.000000
Swedish Krona                  1870  136.666667  66.000000
Tunisian Dinar                   85  150.500000  74.500000
Turkish Lira                    385  145.000000  68.000000
US Dollar                       188  156.000000  67.000000
Ukrainian Hryvna               1870  145.000000  73.500000
Venezuelan Bolivar              885  156.000000  69.000000
West African Franc            18500  130.800000  67.800000

In [9]:
currencyThree = df.groupby(['currency']).agg(avg_value=('value','mean'))

In [10]:
currencyThree

                           avg_value
currency
Argentine Peso           1262.454545
Australian Dollar          26.857143
Bangladeshi Taka          209.666667
Bolivian Boliviano         76.000000
Canadian Dollar            37.000000
Cape Verdean Escudo      1740.000000
Central African Franc    3700.000000
Chilean Peso             7600.000000
Chinese Yuan               31.000000
Colombian Peso          31166.666667
Costa Rican Colon       14666.666667
Czech Koruna             1466.666667
Dobra                      64.166667
East Caribbean Dollar      37.000000
Euro                      126.428571
Georgian Lari              37.000000
Icelandic Krona          4125.000000
Indonesian Rupiah       26857.142857
Israeli New Shekel         92.500000
Jamaican Dollar          1330.000000
Japanese Yen             4500.000000
Korean Won              16500.000000
Kyrgystani Som            981.428571
Malawian Kwacha          1108.750000
New Zealand Dollar         37.000000
Nigerian Naira            235.625000
Papua New Guinean Kina     31.166667
Peruvian Sol               76.000000
Peso Dominicano           641.666667
Peso Mexicano             311.666667
Peso Uruguayo             552.857143
Philippine Piso           311.666667
Pound Stirling             21.250000
Serbian Dinar             986.666667
South African Rand         76.000000
Swedish Krona             311.666667
Tunisian Dinar             21.250000
Turkish Lira               64.166667
US Dollar                  26.857143
Ukrainian Hryvna          311.666667
Venezuelan Bolivar        126.428571
West African Franc       3700.000000

In [11]:
df1 = pd.read_csv('top-song-durations.csv')

In [12]:
df1.columns

Index(['year', 'artist', 'title', 'duration'], dtype='object')

In [13]:
artist_data = df1.groupby(['year','artist'])

In [14]:
artist_data.first()

,,title,duration
year,artist,,
1923,Paul Whiteman and His Orchestra,Parade of the Wooden Soldiers,00:02:59
1924,Wendell Hall,It Ain't Gonna Rain No Mo',00:03:05
1925,Isham Jones with Ray Miller's Orchestra,I'll See You in My Dreams,00:02:51
1926,Paul Whiteman and His Orchestra,Valencia,00:02:50
1927,Gene Austin,My Blue Heaven,00:02:11
...,...,...,...
2019,Lil Nas X feat. Billy Ray Cyrus,Old Town Road,00:02:37
2020,The Weeknd,Blinding Lights,00:03:20
2021,Dua Lipa,Levitating,00:03:23
2022,Glass Animals,Heat Waves,00:03:58
2023,Morgan Wallen,Last Night,00:02:43

In [15]:
new_df1 = df1.where(df1['year'] >= 1980).dropna()

In [16]:
artTwo = new_df1.groupby(['year','artist'])

In [17]:
artTwo.first()

,,title,duration
year,artist,,
1980.0,Blondie,Call Me,00:03:32
1981.0,Kim Carnes,Bette Davis Eyes,00:03:48
1982.0,Olivia Newton-John,Physical,00:03:44
1983.0,The Police,Every Breath You Take,00:03:56
1984.0,Prince,When Doves Cry,00:03:47
1985.0,Wham!,Careless Whisper,00:05:04
1986.0,Dionne & Friends,That’s What Friends Are For,00:04:15
1987.0,The Bangles,Walk Like an Egyptian,00:03:24
1988.0,George Michael,Faith,00:03:16
1989.0,Chicago,Look Away,00:04:02
1990.0,Wilson Phillips,Hold On,00:03:42
1991.0,Bryan Adams,(Everything I Do) I Do It for You,00:04:06
1992.0,Boyz II Men,End of the Road,00:04:13
1993.0,Whitney Houston,I Will Always Love You,00:02:54
1994.0,Ace of Base,The Sign,00:03:08
1995.0,Coolio feat. L.V.,Gangsta’s Paradise,00:04:04
1996.0,Los Del Río,Macarena,00:04:12
1997.0,Elton John,Candle in the Wind,00:03:50
1998.0,Next,Too Close,00:04:20
1999.0,Cher,Believe,00:03:59
2000.0,Faith Hill,Breathe,00:04:09
2001.0,Lifehouse,Hanging by a Moment,00:03:36
2002.0,Nickelback,How You Remind Me,00:03:43
2003.0,50 Cent,In Da Club,00:03:13
2004.0,Usher feat. Lil Jon & Ludacris,Yeah!,00:04:13
2005.0,Mariah Carey,We Belong Together,00:03:21
2006.0,Daniel Powter,Bad Day,00:03:55
2007.0,Beyoncé,Irreplaceable,00:03:47
2008.0,Flo Rida feat. T-Pain,Low,00:03:50
2009.0,The Black Eyed Peas,Boom Boom Pow,00:03:38
2010.0,Kesha,Tik Tok,00:03:14
2011.0,Adele,Rolling in the Deep,00:03:48
2012.0,Gotye feat. Kimbra,Somebody That I Used to Know,00:04:05
2013.0,Macklemore & Ryan Lewis feat. Wanz,Thrift Shop,00:03:55
2014.0,Pharrell Williams,Happy,00:03:53
2015.0,Mark Ronson feat. Bruno Mars,Uptown Funk!,00:03:55
2016.0,Justin Bieber,Love Yourself,00:03:53
2017.0,Ed Sheeran,Shape of You,00:03:54
2018.0,Drake,God’s Plan,00:03:19
2019.0,Lil Nas X feat. Billy Ray Cyrus,Old Town Road,00:02:37
2020.0,The Weeknd,Blinding Lights,00:03:20
2021.0,Dua Lipa,Levitating,00:03:23
2022.0,Glass Animals,Heat Waves,00:03:58
2023.0,Morgan Wallen,Last Night,00:02:43

The artist data shows the name of the artist and the year between 1980 and 2023.

In [18]:
df1.groupby(['year', 'artist']).agg(total_duration = ('duration','sum'))

                                             total_duration
year artist
1923 Paul Whiteman and His Orchestra               00:02:59
1924 Wendell Hall                                  00:03:05
1925 Isham Jones with Ray Miller's Orchestra       00:02:51
1926 Paul Whiteman and His Orchestra               00:02:50
1927 Gene Austin                                   00:02:11
...                                                     ...
2019 Lil Nas X feat. Billy Ray Cyrus               00:02:37
2020 The Weeknd                                    00:03:20
2021 Dua Lipa                                      00:03:23
2022 Glass Animals                                 00:03:58
2023 Morgan Wallen                                 00:02:43

[101 rows x 1 columns]

In [20]:
song_data = df1.groupby(['year','artist','title'])

In [21]:
song_data.first()

                                                                            duration
year artist                                  title
1923 Paul Whiteman and His Orchestra         Parade of the Wooden Soldiers  00:02:59
1924 Wendell Hall                            It Ain't Gonna Rain No Mo'     00:03:05
1925 Isham Jones with Ray Miller's Orchestra I'll See You in My Dreams      00:02:51
1926 Paul Whiteman and His Orchestra         Valencia                       00:02:50
1927 Gene Austin                             My Blue Heaven                 00:02:11
...                                                                              ...
2019 Lil Nas X feat. Billy Ray Cyrus         Old Town Road                  00:02:37
2020 The Weeknd                              Blinding Lights                00:03:20
2021 Dua Lipa                                Levitating                     00:03:23
2022 Glass Animals                           Heat Waves                     00:03:58
2023 Morgan Wallen                           Last Night                     00:02:43

[101 rows x 1 columns]

In [35]:
df['area'] = df.eval('length * width')

In [44]:
df.style.background_gradient(cmap='Purples')

In [37]:
df1.style.background_gradient(cmap='gist_rainbow')